language: php

php:
  - 5.5
  - 5.6

env:
  - MONGO_VERSION=1.2.11
  - MONGO_VERSION=1.3.6

services: mongodb

before_script:
  - pecl install -f mongo-${MONGO_VERSION}
  - phpenv rehash
  - composer --dev install

script: phpunit
