language: php

php:
  - 5.5
  - 5.6

env:
  - MONGO_VERSION=1.6.5
  - MONGO_VERSION=1.5.8

services: mongodb

before_script:
  - yes '' | pecl install -f mongo-${MONGO_VERSION}
  - phpenv rehash
  - composer self-update
  - composer install

script: phpunit
