language: php

services: mongodb

sudo: true

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

addons:
  apt:
    packages:
    - cmake
    - libdouble-conversion-dev
    - libjemalloc-dev
    - libtbb-dev

before_script:
  - ci/setup.sh

script: vendor/bin/phpunit
