language: php

services: mongodb

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - yes "" | pecl install mongodb
  - yes "" | pecl install APCu
  - ./composer.phar install

script: vendor/bin/phpunit
