language: php

sudo: required

php:
  - 5.5
  - 5.6
  - hhvm

env:
  # Current we only support 1.4.5 because of hhvm and mongofill
  - MONGO_VERSION=1.4.5 

services: mongodb

before_script:
  - ./setup_mongo.sh
  - composer self-update
  - composer install

script: phpunit
