language: php

php:
  - 5.5
  - 5.6
  - hhvm

env:
  - MONGO_VERSION=1.4.5

services: mongodb

before_script:
  # - yes '' | pecl install -f mongo-${MONGO_VERSION}
  # - phpenv rehash
  - phpenv config-add mongo-php.ini || cat mongo-php.ini >> /etc/hhvm/php.ini
  - composer self-update
  - composer install

script: phpunit
