language: php

sudo: required

#php:
#  - 5.5
#  - 5.6
#  - hhvm-nightly

#env:
#  - MONGO_VERSION=1.4.5
#  - MONGO_VERSION=1.5.8
#  - MONGO_VERSION=1.6.6
#  - MONGO_VERSION=mongofill-hhvm
#  - MONGO_VERSION=mongofill

services: mongodb

before_script:
  - ./setup.sh

script: phpunit

matrix:
  include:
    - php: hhvm-nightly
      env: MONGO_VERSION=mongofill-hhvm
    - php: hhvm-nightly
      env: MONGO_VERSION=mongofill
    - php: 5.5
      env: MONGO_VERSION=mongofill
    - php: 5.5
      env: MONGO_VERSION=1.4.5
    - php: 5.5
      env: MONGO_VERSION=1.5.8
    - php: 5.5
      env: MONGO_VERSION=1.6.6
    - php: 5.6
      env: MONGO_VERSION=1.4.5
    - php: 5.6
      env: MONGO_VERSION=1.5.8
    - php: 5.6
      env: MONGO_VERSION=1.6.6
