language: php

sudo: required

php:
  - 5.5
  - 5.6
  - hhvm-nightly

env:
  - MONGO_VERSION=1.4.5
  - MONGO_VERSION=1.5.8
  - MONGO_VERSION=1.6.6

services: mongodb

before_script:
  - ./setup_mongo.sh
  - composer self-update
  - composer install

script: phpunit

matrix:
  exclude:
    - php: hhvm-nightly
      env: MONGO_VERSION=1.5.8
    - php: hhvm-nightly
      env: MONGO_VERSION=1.6.6
