language: php

sudo: required

php:
  - hhvm
  - 5.6
  - 5.5

env:
  - MONGO_VERSION=mongofill-hhvm
  - MONGO_VERSION=mongofill
  - MONGO_VERSION=1.6.6
  - MONGO_VERSION=1.5.8
  - MONGO_VERSION=1.4.5

services: mongodb

before_script:
  - ./setup.sh

script: ./vendor/bin/phpunit

matrix:
  exclude:
    - php: hhvm
      env: MONGO_VERSION=1.6.6
    - php: hhvm
      env: MONGO_VERSION=1.5.8
    - php: hhvm
      env: MONGO_VERSION=1.4.5
    - php: 5.5
      env: MONGO_VERSION=mongofill-hhvm
    - php: 5.6
      env: MONGO_VERSION=mongofill-hhvm
