language: php

services: mongodb

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm-3.11
  - hhvm-3.12

before_script:
  - yes "" | pecl install mongodb
  - ./composer.phar install

script: vendor/bin/phpunit
