language: php

sudo: required

services: mongodb

before_script:
  - ./setup.sh

script: phpunit

matrix:
  include:
    - php: hhvm
      env: MONGO_VERSION=mongofill-hhvm
    - php: hhvm
      env: MONGO_VERSION=mongofill
    - php: 5.5
      env: MONGO_VERSION=mongofill
    - php: 5.5
      env: MONGO_VERSION=1.4.5
    - php: 5.5
      env: MONGO_VERSION=1.5.8
    - php: 5.5
      env: MONGO_VERSION=1.6.6
    - php: 5.6
      env: MONGO_VERSION=1.4.5
    - php: 5.6
      env: MONGO_VERSION=1.5.8
    - php: 5.6
      env: MONGO_VERSION=1.6.6
